import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Mint({ connectedWallet, connectWallet }) {
  const mintMemoryCard = async () => {
    console.log(`minty minty to ${connectedWallet}`);
  };

  console.log(connectedWallet);

  return (
    <div className={styles.container}>
      <Head>
        <title>Web3 NES Emulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {connectedWallet ? (
          <button onClick={mintMemoryCard}>Mint Memory Card</button>
        ) : (
          <button onClick={connectWallet}>Connect Wallet</button>
        )}
      </main>
    </div>
  );
}
